name: Setup MariaDB
inputs:
  mariadb-version:
    description: The MariaDB version to download (if necessary) and use
  database:
    description: Database to create
runs:
  using: node16
  main: index.js
