name: Setup MariaDB
description: Setup MariaDB in github workflow
inputs:
  mariadb-version:
    description: The MariaDB version to download (if necessary) and use
  database:
    description: Database to create
  downloaddir:
    description: Directory to cache MariaDB data
    required: false
    default: ".cache/mariadb"
  mirror:
    description: Server URL to download from (replaces dlm.mariadb.com)
    required: false
    default: "https://dlm.mariadb.com"
  download_getopt:
    description: Get options added to the download url (to allow limiting downloads from mirror)
    required: false
    default: ""
runs:
  using: node20
  main: index.js
